{{- if .Values.certs.grpc.create }}
{{ $fullname := include "fullname" . }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ $fullname }}-grpc-issuer
  # annotations:
    # "helm.sh/hook": post-install,post-upgrade
    # "helm.sh/hook-weight": "3"
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ca:
    secretName: {{ .Values.certs.grpc.ca.secretName }}
{{- end }}
